/zed/zed_driver:
  ros__parameters:
    autostart: true
    camera_settings_path: ""
    confidence: 20
    depth_max_distance: 5.0
    depth_min_distance: 0.5
    depth_mode: NEURAL
    depth_rate: 1
    depth_resolution:
      - 480
      - 270
    depth_stabilization: 1
    eigen_max_cores: 4
    enable_tracking: true
    fps: 30
    imu_filters_sampling_time: 0.0025
    imu_filters_zoh_steps: 1000
    imu_filters_order: 2
    imu_filters_low_freqs:
      - 0.5
      - 0.5
    imu_filters_high_freqs:
      - 10.0
      - 10.0
    imu_sampling_time: 2500
    link_namespace: ""
    odometry_frame: odom
    publish_tf: true
    resolution: VGA
    roi_box_sizes:
      - 4.0
      - 2.0
      - 2.0
    sd_resolution:
      - 640
      - 360
    serial_number: -1
    stream_hd: false
    streaming_adaptative_bitrate: true
    streaming_bitrate: 6000
    streaming_chunk_size: 16084
    streaming_codec: ""
    streaming_gop_size: 30
    streaming_sender_ip: ""
    streaming_sender_port: 30000
    streaming_target_fps: 30
    svo_compression: H264
    svo_file: ''
    svo_record: false
    svo_transcode_stream: false
    texture_confidence: 100
    tracking_depth_min_range: -1.0
    tracking_enable_area_memory: true
    tracking_enable_imu_fusion: true
    tracking_enable_pose_smoothing: true
    tracking_set_gravity_as_origin: true
    use_sim_time: false
    verbose: true
    video_rate: 10
