header_include_path: zed_driver/zed_driver.hpp
namespace: ZEDDriver
node_class_name: ZEDDriverNode

params:
  autostart:
    type: bool
    default_value: true
    description: "Start the camera on node startup"
    constraints: "Cannot be changed after node startup"
    read_only: true
    var_name: autostart_

  base_link_name:
    type: string
    default_value: base_link
    description: "Base link name"
    constraints: "Must be a valid frame"
    read_only: true
    var_name: base_link_name_

  camera_settings_path:
    type: string
    default_value: ""
    description: "Path to the ZED camera settings file"
    constraints: "Changes require camera restart, must be a valid file path"
    read_only: false

  confidence:
    type: integer
    default_value: 50
    min_value: 0
    max_value: 100
    step: 1
    description: "Depth confidence threshold"
    constraints: "Must be a valid confidence threshold for the ZED camera"
    read_only: false
    var_name: confidence_

  depth_max_distance:
    type: double
    default_value: 5.0
    min_value: 1.0
    max_value: 20.0
    step: 0.0
    description: "Maximum depth distance [m]"
    constraints: "Changes require camera restart, must be a valid maximum depth distance for the ZED camera"
    read_only: false

  depth_min_distance:
    type: double
    default_value: 0.7
    min_value: 0.1
    max_value: 1.0
    step: 0.0
    description: "Minimum depth distance [m]"
    constraints: "Changes require camera restart, must be a valid minimum depth distance for the ZED camera, may impact performance"
    read_only: false

  depth_mode:
    type: string
    default_value: NEURAL
    description: "Depth mode"
    constraints: "Changes require camera restart, must be a valid depth mode for the ZED camera"
    read_only: false
    validator: validate_depth_mode

  depth_rate:
    type: integer
    default_value: 0
    min_value: -1
    max_value: 100
    step: 1
    description: "Depth stream publishing rate (for undersampling)"
    constraints: "Changes require camera restart, 0 or >=fps mean no undersampling, -1 means no depth data processing"
    read_only: false
    var_name: depth_rate_

  depth_resolution:
    type: integer_array
    default_value:
      - 768
      - 432
    min_value: 0
    max_value: 1920
    step: 1
    description: "Depth map resolution (width, height)"
    constraints: "Changes require camera restart, must be a valid depth map resolution for the ZED camera"
    read_only: false
    var_name: depth_resolution_

  depth_stabilization:
    type: integer
    default_value: 1
    min_value: 0
    max_value: 100
    step: 1
    description: "Depth stabilization"
    constraints: "Changes require camera restart, must be a valid depth stabilization value for the ZED camera"
    read_only: false

  eigen_max_cores:
    type: integer
    default_value: 4
    min_value: 0
    max_value: 16
    step: 1
    description: "Maximum number of cores to use for Eigen library"
    constraints: "Changes require full restart, 0 means no change, must be a valid number of cores depending on the system, pay attention to set this to the same amount if you load this node with others that do the same"
    read_only: true

  enable_tracking:
    type: bool
    default_value: false
    description: "Enables tracking module"
    constraints: "Can only be changed while the camera is not active"
    read_only: false
    validator: validate_enable_tracking

  fps:
    type: integer
    default_value: 30
    min_value: 15
    max_value: 100
    step: 1
    description: "Frame rate of the camera"
    constraints: "Changes require camera restart, must be a valid frame rate for the ZED camera"
    read_only: false
    validator: validate_fps

  imu_filters_sampling_time:
    type: double
    default_value: 0.033333
    min_value: 0.001
    max_value: 1.0
    step: 0.0
    description: "IMU filters sampling time [s]"
    constraints: "Changes require camera restart."
    read_only: false
    var_name: imu_filters_sampling_time_

  imu_filters_zoh_steps:
    type: integer
    default_value: 1000
    min_value: 2
    max_value: 1000000
    step: 1
    description: "IMU filters ZOH integral steps"
    constraints: "Changes require camera restart"
    read_only: false
    var_name: imu_filters_zoh_steps_

  imu_filters_order:
    type: integer
    default_value: 2
    min_value: 1
    max_value: 10
    step: 1
    description: "IMU filters order"
    constraints: "Changes require camera restart"
    read_only: false
    var_name: imu_filters_order_

  imu_filters_low_freqs:
    type: double_array
    default_value:
      - 0.5
      - 0.5
    min_value: 0.0
    max_value: 1000.0
    step: 0.0
    description: "IMU filters low frequencies [Hz]"
    constraints: "Changes require camera restart"
    read_only: false
    var_name: imu_filters_low_freqs_

  imu_filters_high_freqs:
    type: double_array
    default_value:
      - 10.0
      - 10.0
    min_value: 0.0
    max_value: 1000.0
    step: 0.0
    description: "IMU filters high frequencies [Hz]"
    constraints: "Changes require camera restart"
    read_only: false
    var_name: imu_filters_high_freqs_

  link_namespace:
    type: string
    default_value: ""
    description: "Namespace for the zedm link, including the last trailing slash"
    constraints: "Must be a valid link namespace."
    read_only: true
    var_name: link_namespace_

  odometry_frame:
    type: string
    default_value: odom
    description: "Full frame id of the robot's odometry frame"
    constraints: ""
    read_only: true
    var_name: odom_frame_

  publish_tf:
    type: bool
    default_value: false
    description: "Publishes the odom -> base_link TF"
    constraints: ""
    read_only: false
    var_name: publish_tf_

  record_path:
    type: string
    default_value: ""
    description: "Path to the folder where to save video frames"
    constraints: "Must be a valid path, if empty no recording will be done"
    read_only: false
    var_name: record_path_

  resolution:
    type: string
    default_value: HD720
    description: "Camera resolution"
    constraints: "Changes require camera restart, must be a valid resolution for the ZED camera"
    read_only: false
    validator: validate_resolution

  roi_box_sizes:
    type: double_array
    default_value:
      - 2.0
      - 3.0
      - 2.0
    min_value: 0.0
    max_value: 20.0
    step: 0.0
    description: "Point clouds ROI box sizes (X, Y, Z) [m]"
    constraints: "Sizes are intended in NWU frame originating at the bottom right corner of the box"
    read_only: false
    var_name: roi_box_sizes_

  sd_resolution:
    type: integer_array
    default_value:
      - 768
      - 432
    min_value: 0
    max_value: 1920
    step: 1
    description: "SD image resolution (width, height)"
    constraints: "Changes require camera restart, must be a valid SD image resolution for the ZED camera"
    read_only: false
    var_name: sd_resolution_

  serial_number:
    type: integer
    default_value: -1
    min_value: -1
    max_value: 2147483647
    step: 1
    description: "Serial number of the camera to open"
    constraints: "Must be a valid serial number, or -1 to open the first available camera"
    read_only: false

  stream_hd:
    type: bool
    default_value: true
    description: "Enables HD image streaming"
    constraints: "Changes might require stream restart if artifacts are present"
    read_only: false
    var_name: stream_hd_

  streaming_adaptative_bitrate:
    type: bool
    default_value: true
    description: "Enables adaptative bitrate streaming"
    constraints: "Changes require camera restart, works only on Jetson devices"
    read_only: false

  streaming_bitrate:
    type: integer
    default_value: 6000
    min_value: 100
    max_value: 30000
    step: 1
    description: "Streaming bitrate [kbps]"
    constraints: "Changes require camera restart, must be a valid bitrate for the ZED camera"
    read_only: false

  streaming_chunk_size:
    type: integer
    default_value: 16084
    min_value: 1024
    max_value: 65000
    step: 1
    description: "Streaming chunk size [bytes]"
    constraints: "Changes require camera restart, lower this value if network generates a lot of packet loss"
    read_only: false

  streaming_codec:
    type: string
    default_value: ""
    description: "Streaming codec"
    constraints: "Changes require camera restart, can either be 'H264' or 'H265', leave blank to disable streaming/act as receiver"
    read_only: false
    validator: validate_streaming_codec

  streaming_gop_size:
    type: integer
    default_value: 30
    min_value: -1
    max_value: 256
    step: 1
    description: "Streaming GOP size"
    constraints: "Changes require camera restart, -1 will enable an adaptive mode limited to 2 seconds"
    read_only: false

  streaming_sender_ip:
    type: string
    default_value: ""
    description: "Streaming sender IP address"
    constraints: "Changes require camera restart, set together with codec='' to act as receiver"
    read_only: false

  streaming_sender_port:
    type: integer
    default_value: 30000
    min_value: 1024
    max_value: 65535
    step: 1
    description: "Streaming sender port"
    constraints: "Changes require camera restart"
    read_only: false

  streaming_target_fps:
    type: integer
    default_value: 30
    min_value: 1
    max_value: 100
    step: 1
    description: "Streaming target FPS"
    constraints: "Changes require camera restart, must be >= fps, otherwise will be set at fps"
    read_only: false

  svo_compression:
    type: string
    default_value: "H264"
    description: "Compression mode for SVO file recording"
    constraints: "Changes require camera restart, can either be 'LOSSLESS', 'H264', 'H264_LOSSLESS', 'H265', or 'H265_LOSSLESS'"
    read_only: false
    validator: validate_svo_compression

  svo_file:
    type: string
    default_value: ""
    description: "SVO file to use"
    constraints: "Changes require camera restart, leave empty to disable SVO module"
    read_only: false

  svo_record:
    type: bool
    default_value: false
    description: "Enables recording to or reading from an SVO file"
    constraints: "Changes require camera restart"
    read_only: false

  svo_transcode_stream:
    type: bool
    default_value: false
    description: "Enables NVENC transcoding of an RTP remote camera stream to an SVO file for recording"
    constraints: "Changes require camera restart"
    read_only: false

  texture_confidence:
    type: integer
    default_value: 100
    min_value: 0
    max_value: 100
    step: 1
    description: "Texture confidence threshold"
    constraints: "Must be a valid texture confidence threshold for the ZED camera"
    read_only: false
    var_name: texture_confidence_

  tracking_depth_min_range:
    type: double
    default_value: -1.0
    min_value: -1.0
    max_value: 20.0
    step: 0.0
    description: "Minimum depth range for tracking [m], to exclude nearby static objects"
    constraints: "Changes require camera restart, -1.0 disables this feature"
    read_only: false

  tracking_enable_area_memory:
    type: bool
    default_value: true
    description: "Enables area memory, improving tracking accuracy"
    constraints: "Changes require camera restart"
    read_only: false

  tracking_enable_imu_fusion:
    type: bool
    default_value: true
    description: "Enables IMU fusion for positional tracking"
    constraints: "Changes require camera restart"
    read_only: false

  tracking_enable_pose_smoothing:
    type: bool
    default_value: true
    description: "Enables pose smoothing"
    constraints: "Changes require camera restart"
    read_only: false

  tracking_set_gravity_as_origin:
    type: bool
    default_value: true
    description: "Whether to override 2 of the 3 rotations from initial world transform using IMU gravity"
    constraints: "Changes require camera restart"
    read_only: false

  verbose:
    type: bool
    default_value: true
    description: "Enables additional logging"
    constraints: ""
    read_only: false
    var_name: verbose_

  video_rate:
    type: integer
    default_value: 0
    min_value: 0
    max_value: 100
    step: 1
    description: "Video streams publishing rate (for undersampling)"
    constraints: "Changes require camera restart, 0 or >fps mean no undersampling"
    read_only: false
    var_name: video_rate_
